name = "kotisivu-cloudflare"
type = "webpack"
account_id = ""
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2025-03-20"

[site]
bucket = "."
entry-point = "workers-site"
